[package]
name = "knf-rs-new"
version = "0.2.5"
edition = "2021"
license = "MIT"
description = "fbank features extractor without external dependencies"

[dependencies]
knf-rs-sys-new = "0.2.4"
eyre = "0.6.12"
ndarray = "0.16"


[features]
default = []
